language: java
jdk:
  - oraclejdk8
script:
 - gradle cucumber
 - gradle test
 - gradle junitPlatformTest
 - gradle jacocoTestReport

before_script:
- chmod a+x gradlew

after_success:
- bash <(curl -s https://codecov.io/bash)